networks:
  kafka-net:
    name: kafka-net
    driver_opts:
      com.docker.network.driver.mtu: "1376"

services:
  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:8.2.0
    restart: unless-stopped
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    networks:
      - kafka-net
    extends:
      file: docker-compose.base.yml
      service: base
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "2.0"

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-net
    extends:
      file: docker-compose.base.yml
      service: base

volumes:
  kafka_data:
